reduced = [
    (None, 'Darwin'),
    (None, 'Kalgoorlie, Goldfields & Esperance'),
    ('Russia & Eastern Europe', 'Europe & Russia'),
    (None, 'Perth'),
    (None, 'Hobart'),
    ('CBD, Inner & Western Suburbs', 'Perth'),
    (None, 'Mandurah & Peel'),
    (None, 'Launceston & North East'),
    (None, 'Bendigo, Goldfields & Macedon Ranges'),
    (None, 'Somerset & Lockyer'),
    (None, 'Wagga Wagga & Riverina'),
    ('CBD, Inner West & Eastern Suburbs', 'Sydney'),
    (None, 'Horsham & Grampians'),
    (None, 'South West Coast VIC'),
    (None, 'Far West & North Central NSW'),
    ('Northern Suburbs', 'Melbourne'),
    (None, 'Sunshine Coast'),
    (None, 'Northern QLD'),
    (None, 'Rockhampton & Capricorn Coast'),
    ('CBD & Inner Suburbs', 'Melbourne'),
    (None, 'Tumut, Snowy & Monaro'),
    (None, 'Asia Pacific'),
    (None, 'West Gippsland & Latrobe Valley'),
    ('Bayside & South Eastern Suburbs', 'Melbourne'),
    (None, 'Broome & Kimberley'),
    (None, 'Northam & Wheatbelt'),
    (None, 'Adelaide'),
    (None, 'Europe & Russia'),
    (None, 'Yorke Peninsula & Clare Valley'),
    ('North West & Hills District', 'Sydney'),
    (None, 'Mildura & Murray'),
    (None, 'Lismore & Far North Coast'),
    ('Eastern Suburbs', 'Perth'),
    ('Fremantle & Southern Suburbs', 'Perth'),
    (None, 'Albury Area'),
    (None, 'Coffs Harbour & North Coast'),
    (None, 'Port Macquarie & Mid North Coast'),
    ('Southern Suburbs & Logan', 'Brisbane'),
    (None, 'Alice Springs & Central Australia'),
    (None, 'ACT'),
    (None, 'Gladstone & Central QLD'),
    (None, 'Bundaberg & Wide Bay Burnett'),
    (None, 'Devonport & North West'),
    ('Bayside & Eastern Suburbs', 'Brisbane'),
    ('Eastern Suburbs', 'Melbourne'),
    (None, 'Coober Pedy & Outback SA'),
    ('Ryde & Macquarie Park', 'Sydney'),
    (None, 'Shepparton & Goulburn Valley'),
    ('Western Suburbs & Ipswich', 'Brisbane'),
    (None, 'Ballarat & Central Highlands'),
    (None, 'Fleurieu Peninsula & Kangaroo Island'),
    ('PNG & Pacific Islands', 'Asia Pacific'),
    (None, 'Dubbo & Central NSW'),
    (None, 'Toowoomba & Darling Downs'),
    (None, 'Cairns & Far North'),
    ('North Shore & Northern Beaches', 'Sydney'),
    (None, 'Gosford & Central Coast'),
    ('China, Hong Kong & Taiwan', 'Asia Pacific'),
    (None, 'Richmond & Hawkesbury'),
    ('Northern Suburbs & Joondalup', 'Perth'),
    (None, 'Mackay & Coalfields'),
    ('Southern Suburbs & Sutherland Shire', 'Sydney'),
    (None, 'Bairnsdale & Gippsland'),
    (None, 'Mt Gambier & Limestone Coast'),
    (None, 'Geraldton, Gascoyne & Midwest'),
    ('Parramatta & Western Suburbs', 'Sydney'),
    (None, 'Bunbury & South West'),
    (None, 'Mornington Peninsula & Bass Coast'),
    (None, 'Yarra Valley & High Country'),
    (None, 'Newcastle, Maitland & Hunter'),
    (None, 'Port Hedland, Karratha & Pilbara'),
    ('South West & M5 Corridor', 'Sydney'),
    (None, 'Katherine & Northern Australia'),
    (None, 'Western QLD'),
    (None, 'Wollongong, Illawarra & South Coast'),
    (None, 'Tamworth & North West NSW'),
    ('CBD & Inner Suburbs', 'Brisbane'),
    (None, 'Hervey Bay & Fraser Coast'),
    (None, 'Sydney'),
    (None, 'Gold Coast'),
    (None, 'Albany & Great Southern'),
    (None, 'Adelaide Hills & Barossa'),
    (None, 'Riverland & Murray Mallee'),
    (None, 'Melbourne'),
    (None, 'Blue Mountains & Central West'),
    (None, 'Southern Highlands & Tablelands'),
    ('Middle East & North Africa', 'Middle East & Africa'),
    ('Rockingham & Kwinana', 'Perth'),
    (None, 'Whyalla & Eyre Peninsula'),
    ('Northern Suburbs', 'Brisbane'),
    ('Western Suburbs', 'Melbourne'),
    (None, 'Brisbane'),
    (None, 'Central & South East TAS')]

standardPostcode = [('Alice Springs & Central Australia', 872),
                    ('Brisbane', 4000),
                    ('Darwin', 800),
                    ('Melbourne', 3000),
                    ('Perth', 6000),
                    ('Sydney', 2000),
                    ('Katherine & Northern Australia', 850),
                    ('Adelaide Hills & Barossa', 5131),
                    ('Albany & Great Southern', 6316),
                    ('Albury Wodonga & Murray', 2640),
                    ('Albury Area', 2640),
                    ('Adelaide', 5000),
                    ('Canberra', 2600),
                    ('Gold Coast', 4207),
                    ('Hobart', 7000),
                    ('Bairnsdale & Gippsland', 3847),
                    ('Ballarat & Central Highlands', 3321),
                    ('Bayside & Eastern Suburbs Brisbane', 4157),
                    ('Bayside & South Eastern Suburbs Melbourne', 3145),
                    ('Bendigo, Goldfields & Macedon Ranges', 3334),
                    ('Blue Mountains & Central West', 2773),
                    ('Brisbane CBD & Inner Suburbs Brisbane', 4000),
                    ('Broome & Kimberley', 6725),
                    ('Bunbury & South West', 6218),
                    ('Bundaberg & Wide Bay Burnett', 4621),
                    ('Cairns & Far North', 4849),
                    ('Central & South East TAS', 7027),
                    ('Coffs Harbour & North Coast', 2441),
                    ('Coober Pedy & Outback SA', 5440),
                    ('Devonport & North West', 7256),
                    ('Dubbo & Central NSW', 2357),
                    ('Eastern Suburbs Melbourne', 3101),
                    ('Eastern Suburbs Perth', 6051),
                    ('Far West & North Central NSW', 2386),
                    ('Fleurieu Peninsula & Kangaroo Island', 5157),
                    ('Fremantle & Southern Suburbs Perth', 6102),
                    ('Geelong & Great Ocean Road', 3212),
                    ('Geraldton, Gascoyne & Midwest', 6513),
                    ('Gladstone & Central QLD', 4420),
                    ('Gosford & Central Coast', 2083),
                    ('Goulburn & Southern Tablelands', 2575),
                    ('Southern Highlands & Tablelands', 2575),
                    ('Hervey Bay & Fraser Coast', 4570),
                    ('Horsham & Grampians', 3293),
                    ('Kalgoorlie, Goldfields & Esperance', 6429),
                    ('Launceston & North East', 7190),
                    ('Lismore & Far North Coast', 2469),
                    ('Mackay & Coalfields', 4705),
                    ('Mandurah & Peel', 6121),
                    ('Melbourne CBD & Inner Suburbs Melbourne', 3000),
                    ('Mildura & Murray', 3490),
                    ('Mornington Peninsula & Bass Coast', 3911),
                    ('Mt Gambier & Limestone Coast', 5259),
                    ('Mt Isa & Western', 4417),
                    ('Newcastle, Maitland & Hunter', 2264),
                    ('North Shore & Northern Beaches Sydney', 2060),
                    ('North West & Hills District Sydney', 2077),
                    ('Northam & Wheatbelt', 6041),
                    ('Northern Suburbs & Joondalup Perth', 6017),
                    ('Northern Suburbs Brisbane', 4019),
                    ('Northern Suburbs Melbourne', 3043),
                    ('Parramatta & Western Suburbs Sydney', 2116),
                    ('Perth CBD, Inner & Western Suburbs Perth', 6000),
                    ('Port Hedland, Karratha & Pilbara', 6710),
                    ('Port Macquarie & Mid North Coast', 2424),
                    ('Richmond & Hawkesbury', 2753),
                    ('Riverland & Murray Mallee', 5236),
                    ('Rockhampton & Capricorn Coast', 4699),
                    ('Rockingham & Kwinana Perth', 6165),
                    ('Ryde & Macquarie Park Sydney', 2112),
                    ('Shepparton & Goulburn Valley', 3558),
                    ('Somerset & Lockyer', 4311),
                    ('South West & M5 Corridor Sydney', 2162),
                    ('Southern Suburbs & Logan Brisbane', 4114),
                    ('Southern Suburbs & Sutherland Shire Sydney', 2133),
                    ('Sunshine Coast', 4517),
                    ('Sydney CBD, Inner West & Eastern Suburbs Sydney', 2000),
                    ('Tamworth & North West NSW', 2338),
                    ('Toowoomba & Darling Downs', 4350),
                    ('Townsville & Northern', 4800),
                    ('Traralgon & La Trobe Valley', 3781),
                    ('Tumut, Snowy & Monaro', 2621),
                    ('Wagga Wagga & Riverina', 2590),
                    ('Western Suburbs & Ipswich Brisbane', 4300),
                    ('Western Suburbs Melbourne', 3011),
                    ('Whyalla & Eyre Peninsula', 5600),
                    ('Wollongong, Illawarra & South Coast', 2500),
                    ('Yarra Valley & High Country', 3116),
                    ('Yorke Peninsula & Clare Valley', 5374),
                    ('South West Coast VIC', 3220),
                    ('West Gippsland & Latrobe Valley', 3844),
                    ('ACT', 2601)
                    ]
for suburb, city in reduced:
    found = False
    for cityPC, postcode in standardPostcode:
        if city == cityPC:
            print(city, postcode)
            found = True
            break
    if not found:
        print(city)